export const authConstants = {
  SIGNIN_REQUEST:'SIGNIN_REQUEST',
  SIGNIN_SUCCESS:'SIGNIN_SUCCESS',
  SIGNIN_FAILURE:'SIGNIN_FAILURE',
  SIGNOUT_REQUEST:'SIGNOUT_REQUEST',
  SIGNOUT_SUCCESS:'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE:'SIGNOUT_FAILURE',
}

export const getData = {
  GETDATA_REQUEST:'GETDATA_REQUEST',
  GETDATA_SUCCESS:'GETDATA_SUCCESS',
  GETDATA_FAILURE:'GETDATA_FAILURE',
}

export const addEducation = {
  ADD_EDUCATION_REQUEST:'ADD_EDUCATION_REQUEST',
  ADD_EDUCATION_SUCCESS:'ADD_EDUCATION_SUCCESS',
  ADD_EDUCATION_FAILURE:'ADD_EDUCATION_FAILURE',
}

export const addWorkExperience = {
  ADD_WORK_EXP_REQUEST:'ADD_WORK_EXP_REQUEST',
  ADD_WORK_EXP_SUCCESS:'ADD_WORK_EXP_SUCCESS',
  ADD_WORK_EXP_FAILURE:'ADD_WORK_EXP_FAILURE',
}